"""remove test field in transport model

Revision ID: 8594665c6726
Revises: 2e53426ffb42
Create Date: 2024-06-10 11:02:10.850454

"""
from typing import Sequence, Union

from alembic import op
from sqlmodel import SQLModel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8594665c6726'
down_revision: Union[str, None] = '2e53426ffb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
